CREATE DATABASE QLNH_test
GO
USE QLNH_test
GO

CREATE TABLE KHACHHANG
(
    CMND VARCHAR(20), -- neu de cmmd làm ID thì có đảm bảo bảo mật ko ??
	TenKH NVARCHAR(30),
	NgaySinh DATE,
	GioiTinh BIT, 
	DiaChi NVARCHAR(50),
	SoDienThoai VARCHAR(10), 
	PRIMARY KEY(CMND)
)
GO


CREATE TABLE LoaiTK
(
	id INT IDENTITY PRIMARY KEY,
	TenLoaiTK NVARCHAR(30) NOT NULL DEFAULT N'Thông Thường'
)
GO

CREATE TABLE TAIKHOAN
(
    SoTK VARCHAR(20) PRIMARY KEY,
	MaKH VARCHAR(20) NOT NULL,
	TenDangNhap NVARCHAR(30) UNIQUE NOT NULL,
	MatKhau VARCHAR(20),
	NgayDangKy DATETIME DEFAULT GETDATE(), --mặc định ngày đăng kí là ngày thực hiện tạo TK
	loaiTK INT NOT NULL,
	SoDu BIGINT DEFAULT 5000000,

	
	FOREIGN KEY (MaKH) REFERENCES dbo.KHACHHANG(CMND),
	FOREIGN KEY(loaiTK)REFERENCES dbo.LoaiTK(id),
)
GO



CREATE TABLE GIAODICH
(
	MaGD VARCHAR(20) PRIMARY KEY,
	SoTK VARCHAR(20) NOT NULL, -- tài khoản nguồn
	LoaiGD NVARCHAR(30),
	NgayGD DATETIME NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY (SoTK) REFERENCES  dbo.TAIKHOAN(SoTK),
)
GO

CREATE TABLE CHITIETGD
(
	id INT IDENTITY PRIMARY KEY,
    MaGD VARCHAR(20) NOT NULL,
	SoTKNhan VARCHAR(20), -- tai khoan thụ hưởng
	SoTien FLOAT,
	GhiChu NVARCHAR(70),
	FOREIGN KEY (MaGD) REFERENCES dbo.GIAODICH(MaGD),
	FOREIGN KEY (SoTKNhan) REFERENCES dbo.TAIKHOAN(SoTK)
)
GO 

