USE BankManager
GO
-- getUserData from accountNummber
SELECT dbo.[TAIKHOAN].[SoTK],dbo.[TAIKHOAN].[SoDu],[dbo].[TAIKHOAN].[NgayDangKy],dbo.[KHACHHANG].* FROM dbo.[KHACHHANG]
FULL OUTER JOIN dbo.[TAIKHOAN] ON [TAIKHOAN].[MaKH] = [KHACHHANG].[MaKH]
LEFT JOIN dbo.[loginAccount] ON [loginAccount].[SoTK] = [TAIKHOAN].[SoTK]
WHERE dbo.[loginAccount].[SoTK] = '9704363636'

-- getTradingHistory by accountNumber

SELECT dbo.[GIAODICH].[LoaiGD], dbo.[CHITIETGD].[NgayGD],dbo.[KHACHHANG].[TenKH] AS [NguoiNhan],dbo.[CHITIETGD].[NoiDung],dbo.[CHITIETGD].[SoTien]
FROM dbo.[CHITIETGD] FULL OUTER JOIN dbo.[GIAODICH] ON [GIAODICH].[MaGD] = [CHITIETGD].[MaGD]
LEFT JOIN dbo.TAIKHOAN ON dbo.GIAODICH.SoTK = '9704363636'
INNER JOIN dbo.[KHACHHANG] ON [KHACHHANG].[MaKH] = [TAIKHOAN].[MaKH] 
WHERE (dbo.[TAIKHOAN].[SoTK] !='9704363636' AND (dbo.GIAODICH.LoaiGD = N'Chuyển Khoản' OR dbo.GIAODICH.LoaiGD = N'Nhận Chuyển Khoản'))
OR (dbo.[TAIKHOAN].[SoTK] ='9704363636' AND (dbo.GIAODICH.LoaiGD = N'Nạp Tiền' OR dbo.GIAODICH.LoaiGD = N'Rút Tiền'))

SELECT dbo.KHACHHANG.TenKH, dbo.TAIKHOAN.SoDu
FROM dbo.KHACHHANG FULL OUTER JOIN dbo.TAIKHOAN ON TAIKHOAN.MaKH = KHACHHANG.MaKH

-- get thu chi 
SET DATEFORMAT DMY SELECT dbo.[TAIKHOAN].[SoTK],SUM(dbo.[CHITIETGD].[SoTien]) AS [NhanVao]
FROM dbo.[TAIKHOAN] right JOIN dbo.[GIAODICH] ON [GIAODICH].[SoTK] = [TAIKHOAN].[SoTK]
RIGHT JOIN dbo.[CHITIETGD] ON [CHITIETGD].[MaGD] = [GIAODICH].[MaGD]
WHERE (dbo.[GIAODICH].[LoaiGD] = N'Nạp Tiền' or dbo.[GIAODICH].[LoaiGD] = N'Nhận Chuyển Khoản') AND (dbo.[CHITIETGD].[NgayGD] BETWEEN  '29/04/2021' AND '01/06/2021')
GROUP BY TAIKHOAN.SoTK HAVING TAIKHOAN.SoTK = '9704686868'

SET DATEFORMAT DMY SELECT dbo.[TAIKHOAN].[SoTK],SUM(dbo.[CHITIETGD].[SoTien]) AS [NhanVao]
FROM dbo.[TAIKHOAN] right JOIN dbo.[GIAODICH] ON [GIAODICH].[SoTK] = [TAIKHOAN].[SoTK]
RIGHT JOIN dbo.[CHITIETGD] ON [CHITIETGD].[MaGD] = [GIAODICH].[MaGD]
WHERE (dbo.[GIAODICH].[LoaiGD] = N'Nạp Tiền' or dbo.[GIAODICH].[LoaiGD] = N'Nhận Chuyển Khoản') AND (dbo.[CHITIETGD].[NgayGD] BETWEEN  '29/04/2021' AND '01/06/2021')
GROUP BY TAIKHOAN.SoTK

SET DATEFORMAT DMY SELECT dbo.[TAIKHOAN].[SoTK],SUM(dbo.[CHITIETGD].[SoTien]) AS [ChiRa]
FROM dbo.[TAIKHOAN] right JOIN dbo.[GIAODICH] ON [GIAODICH].[SoTK] = [TAIKHOAN].[SoTK]
RIGHT JOIN dbo.[CHITIETGD] ON [CHITIETGD].[MaGD] = [GIAODICH].[MaGD]
WHERE (dbo.[GIAODICH].[LoaiGD] = N'Nạp Tiền' or dbo.[GIAODICH].[LoaiGD] = N'Nhận Chuyển Khoản')
AND (dbo.[CHITIETGD].[NgayGD] =  '21/05/21')
GROUP BY [TAIKHOAN].[SoTK]

SELECT dbo.GIAODICH.SoTK,dbo.GIAODICH.LoaiGD, dbo.CHITIETGD.* FROM dbo.[CHITIETGD] LEFT JOIN dbo.GIAODICH ON GIAODICH.MaGD = CHITIETGD.MaGD

SELECT * FROM dbo.[TAIKHOAN]

SELECT dbo.[TAIKHOAN].[SoTK],dbo.[KHACHHANG].*,dbo.[TAIKHOAN].[NgayDangKy],dbo.[TAIKHOAN].[SoDu]
FROM dbo.[KHACHHANG] FULL OUTER JOIN dbo.[TAIKHOAN] ON [TAIKHOAN].[MaKH] = [KHACHHANG].[MaKH]

SELECT dbo.GIAODICH.SoTK,dbo.GIAODICH.LoaiGD,dbo.CHITIETGD.* FROM dbo.GIAODICH LEFT JOIN dbo.CHITIETGD ON CHITIETGD.MaGD = GIAODICH.MaGD
ORDER BY dbo.GIAODICH.MaGD

UPDATE dbo.loginAccount SET loginPassword = 'adminedit' WHERE loginName = 'test1'

SELECT dbo.TAIKHOAN.SoDu AS [truoc] FROM dbo.TAIKHOAN WHERE SoTK = '9704363636'
UPDATE dbo.TAIKHOAN SET SoDu = SoDu + (100 * -1) WHERE SoTK = '9704363636'
SELECT dbo.TAIKHOAN.SoDu AS [sau] FROM dbo.TAIKHOAN WHERE SoTK = '9704363636'

SET DATEFORMAT DMY SELECT dbo.[TAIKHOAN].[SoTK],SUM(dbo.[CHITIETGD].[SoTien]) AS [NhanVao]
FROM dbo.[TAIKHOAN] right JOIN dbo.[GIAODICH] ON [GIAODICH].[SoTK] = [TAIKHOAN].[SoTK]
RIGHT JOIN dbo.[CHITIETGD] ON [CHITIETGD].[MaGD] = [GIAODICH].[MaGD]
WHERE (dbo.[GIAODICH].[LoaiGD] = N'Nạp Tiền' or dbo.[GIAODICH].[LoaiGD] = N'Nhận Chuyển Khoản')
AND (dbo.[CHITIETGD].[NgayGD] BETWEEN  '21/5/21' AND '2/6/21')
GROUP BY [TAIKHOAN].[SoTK]


INSERT INTO dbo.[KHACHHANG]([MaKH],[TenKH],[NgaySinh],[GioiTinh],[DiaChi],[SoDienThoai])
VALUES( '333444555666', N'Nguyễn Tèo','21/12/1997',1,N'Nhà tèo','0868103406')
INSERT INTO dbo.TAIKHOAN(SoTK,MaKH,NgayDangKy,SoDu)
VALUES('0123456789','333444555666',GETDATE(), DEFAULT)
INSERT INTO dbo.[loginAccount](loginName,loginPassword,SoTK)
VALUES('test9','admin','0123456789')


SELECT * FROM dbo.[loginAccount]